sudo: required
services:
  - docker

before_install:
  - docker build -t nagapalanisamy/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nagapalanisamy/multi-docker-test npm run test -- --coverage

after_success:
  - docker build -t nagapalanisamy/multi-client ./client
  - docker build -t nagapalanisamy/multi-nginx ./nginx
  - docker build -t nagapalanisamy/multi-server ./server
  - docker build -t nagapalanisamy/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push it to docker hub
  - docker push nagapalanisamy/multi-client
  - docker push nagapalanisamy/multi-nginx
  - docker push nagapalanisamy/multi-server
  - docker push nagapalanisamy/multi-worker
